package app.eqsweep.core

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.jsonObject

/** Loads parity-vectors.json (generated by core/tools/gen-vectors.mjs from the upstream JS). */
object TestVectors {
    val root: JsonObject by lazy {
        val text = requireNotNull(TestVectors::class.java.getResourceAsStream("/parity-vectors.json")) {
            "parity-vectors.json missing from test resources"
        }.bufferedReader(Charsets.UTF_8).readText()
        Json.parseToJsonElement(text).jsonObject
    }

    /** JSON number, or the string markers "NaN" / "Infinity" / "-Infinity" used for non-finite inputs. */
    fun num(e: JsonElement?): Double = when {
        e == null || e is JsonNull -> Double.NaN
        e is JsonPrimitive && e.isString -> when (e.content) {
            "NaN" -> Double.NaN
            "Infinity" -> Double.POSITIVE_INFINITY
            "-Infinity" -> Double.NEGATIVE_INFINITY
            else -> e.content.toDouble()
        }
        e is JsonPrimitive -> requireNotNull(e.doubleOrNull) { "not a number: $e" }
        else -> error("not a number: $e")
    }

    fun numOrNull(e: JsonElement?): Double? = if (e == null || e is JsonNull) null else num(e)

    fun str(e: JsonElement?): String? = (e as? JsonPrimitive)?.contentOrNull
}
